spring.application.name=quotegeneratorbackend

spring.datasource.url=jdbc:postgresql://localhost:5432/quote_db
spring.datasource.username=postgres
spring.datasource.password=02140322

#?? hibernate ????????? schema.sql??
spring.jpa.hibernate.ddl-auto=none
#?? Spring Boot ????????? schema.sql ? data.sql
spring.sql.init.mode=always

spring.jpa.show-sql=true



