TRUNCATE TABLE quotes RESTART IDENTITY;

INSERT INTO quotes (content, author, category, created_at, updated_at) VALUES
                                                                               ('The best way to predict the future is to create it.', 'Peter Drucker', 'Motivation', NOW(), NOW()),
                                                                               ('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'Motivation', NOW(), NOW()),
                                                                               ('It always seems impossible until it is done.', 'Nelson Mandela', 'Motivation', NOW(), NOW()),
                                                                               ('Believe you can and you are halfway there.', 'Theodore Roosevelt', 'Motivation', NOW(), NOW()),
                                                                               ('Do not wait. The time will never be just right.', 'Napoleon Hill', 'Motivation', NOW(), NOW()),
                                                                               ('The only limit to our realization of tomorrow is our doubts of today.', 'Franklin D. Roosevelt', 'Motivation', NOW(), NOW()),
                                                                               ('Dream big and dare to fail.', 'Norman Vaughan', 'Motivation', NOW(), NOW()),
                                                                               ('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'Motivation', NOW(), NOW()),

                                                                               ('Small progress is still progress.', 'Unknown', 'Growth', NOW(), NOW()),
                                                                               ('Turn your wounds into wisdom.', 'Oprah Winfrey', 'Growth', NOW(), NOW()),
                                                                               ('Difficulties in life are intended to make us better, not bitter.', 'Dan Reeves', 'Growth', NOW(), NOW()),
                                                                               ('In the middle of every difficulty lies opportunity.', 'Albert Einstein', 'Growth', NOW(), NOW()),
                                                                               ('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'Growth', NOW(), NOW()),
                                                                               ('What we think, we become.', 'Buddha', 'Growth', NOW(), NOW()),
                                                                               ('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela', 'Growth', NOW(), NOW()),
                                                                               ('Life is a succession of lessons which must be lived to be understood.', 'Ralph Waldo Emerson', 'Growth', NOW(), NOW()),

                                                                               ('Learning never exhausts the mind.', 'Leonardo da Vinci', 'Learning', NOW(), NOW()),
                                                                               ('Live as if you were to die tomorrow. Learn as if you were to live forever.', 'Mahatma Gandhi', 'Learning', NOW(), NOW()),
                                                                               ('Education is the most powerful weapon which you can use to change the world.', 'Nelson Mandela', 'Learning', NOW(), NOW()),
                                                                               ('The beautiful thing about learning is that no one can take it away from you.', 'B.B. King', 'Learning', NOW(), NOW()),
                                                                               ('An investment in knowledge pays the best interest.', 'Benjamin Franklin', 'Learning', NOW(), NOW()),
                                                                               ('Tell me and I forget. Teach me and I remember. Involve me and I learn.', 'Benjamin Franklin', 'Learning', NOW(), NOW()),
                                                                               ('The more that you read, the more things you will know.', 'Dr. Seuss', 'Learning', NOW(), NOW()),
                                                                               ('The expert in anything was once a beginner.', 'Helen Hayes', 'Learning', NOW(), NOW()),

                                                                               ('Well done is better than well said.', 'Benjamin Franklin', 'Action', NOW(), NOW()),
                                                                               ('Action is the foundational key to all success.', 'Pablo Picasso', 'Action', NOW(), NOW()),
                                                                               ('You miss 100 percent of the shots you do not take.', 'Wayne Gretzky', 'Action', NOW(), NOW()),
                                                                               ('Do one thing every day that scares you.', 'Eleanor Roosevelt', 'Action', NOW(), NOW()),
                                                                               ('Act as if what you do makes a difference. It does.', 'William James', 'Action', NOW(), NOW()),
                                                                               ('Opportunities do not happen. You create them.', 'Chris Grosser', 'Action', NOW(), NOW()),
                                                                               ('If opportunity does not knock, build a door.', 'Milton Berle', 'Action', NOW(), NOW()),
                                                                               ('The secret of getting ahead is getting started.', 'Mark Twain', 'Action', NOW(), NOW()),

                                                                               ('Quality is not an act, it is a habit.', 'Aristotle', 'Wisdom', NOW(), NOW()),
                                                                               ('Happiness depends upon ourselves.', 'Aristotle', 'Wisdom', NOW(), NOW()),
                                                                               ('Everything has beauty, but not everyone sees it.', 'Confucius', 'Wisdom', NOW(), NOW()),
                                                                               ('It does not matter how slowly you go as long as you do not stop.', 'Confucius', 'Wisdom', NOW(), NOW()),
                                                                               ('A goal without a plan is just a wish.', 'Antoine de Saint-Exupéry', 'Wisdom', NOW(), NOW()),
                                                                               ('The purpose of our lives is to be happy.', 'Dalai Lama', 'Wisdom', NOW(), NOW()),
                                                                               ('Everything you can imagine is real.', 'Pablo Picasso', 'Wisdom', NOW(), NOW()),
                                                                               ('Light tomorrow with today.', 'Elizabeth Barrett Browning', 'Wisdom', NOW(), NOW());